#!/bin/bash
REQUIRED=$(curl http://paste.lisp.org/administration/spam-review-required 2>/dev/null)
if [ "$REQUIRED" = "YES" ]
then
	mail -s "Administration reminder for $(date '+%a %b %d')" lisppaste-requests@common-lisp.net << END

There are pastes which have been marked as spam or have been requested
for deletion. Please visit http://paste.lisp.org/administration to
tend to these requests.

END
fi
