(in-package :cl-user)

(defun panacea ()
  (araneida:stop-listening lisppaste::*paste-listener*)
  (ignore-errors (progn
                   (lisppaste:quit-all-connections)
                   (irc:quit specbot::*connection*)
                   (irc:quit cliki::*cliki-connection*)))
  (s-xml-rpc:stop-server (caar s-xml-rpc::*server-processes*))
  (loop for i from 3 below 1025 do (sb-unix:unix-close i))
  (setf sb-impl::*descriptor-handlers* nil)
  (s-xml-rpc:start-xml-rpc-server :port 8185)
  (araneida:start-listening lisppaste::*paste-listener*)
  (lisppaste:hup-all-connections)
  (sleep 5)
  (apply #'cliki::start-cliki-bot "minion" "chat.freenode.net" *minion-channels*)
  (sleep 5)
  (format t "ABOUT TO START SPECBOT.~%")
  (apply #'specbot::start-specbot "specbot" "chat.freenode.net" *specbot-channels*)
  (sleep 5))
